

  pkgconf:
    version_source: "lfs"
    lfs_source_name: "pkgconf"
    arch_pkgbase: "pkgconf"
    repository: "only-core"
    build_order: 31
    enabled: true

  binutils:
    version_source: "lfs"
    lfs_source_name: "binutils"
    arch_pkgbase: "binutils"
    repository: "only-core"
    build_order: 32
    enabled: true

  gperf:
    version_source: "lfs"
    lfs_source_name: "gperf"
    arch_pkgbase: "gperf"
    repository: "only-core"
    build_order: 33
    enabled: true

  libffi:
    version_source: "lfs"
    lfs_source_name: "libffi"
    arch_pkgbase: "libffi"
    repository: "only-core"
    build_order: 34
    enabled: true


  iana-etc:
    version_source: "lfs"
    lfs_source_name: "iana-etc"
    arch_pkgbase: "iana-etc"
    repository: "only-core"
    build_order: 35
    enabled: true

  psmisc:
    version_source: "lfs"
    lfs_source_name: "psmisc"
    arch_pkgbase: "psmisc"
    repository: "only-core"
    build_order: 36
    enabled: true

  less:
    version_source: "lfs"
    lfs_source_name: "less"
    arch_pkgbase: "less"
    repository: "only-core"
    build_order: 37
    enabled: true

  libpipeline:
    version_source: "lfs"
    lfs_source_name: "libpipeline"
    arch_pkgbase: "libpipeline"
    repository: "only-core"
    build_order: 38
    enabled: true

  man-pages:
    version_source: "lfs"
    lfs_source_name: "man-pages"
    arch_pkgbase: "man-pages"
    repository: "only-core"
    build_order: 39
    enabled: true

  gettext:
    version_source: "lfs"
    lfs_source_name: "gettext"
    arch_pkgbase: "gettext"
    repository: "only-core"
    build_order: 40
    enabled: true


  gdbm:
    version_source: "lfs"
    lfs_source_name: "gdbm"
    arch_pkgbase: "gdbm"
    repository: "only-core"
    build_order: 41
    enabled: true

  groff:
    version_source: "lfs"
    lfs_source_name: "groff"
    arch_pkgbase: "groff"
    repository: "only-core"
    build_order: 42
    enabled: true

  texinfo:
    version_source: "lfs"
    lfs_source_name: "texinfo"
    arch_pkgbase: "texinfo"
    repository: "only-core"
    build_order: 43
    enabled: true

  procps-ng:
    version_source: "lfs"
    lfs_source_name: "procps-ng"
    arch_pkgbase: "procps-ng"
    repository: "only-core"
    build_order: 44
    enabled: true

  inetutils:
    version_source: "lfs"
    lfs_source_name: "inetutils"
    arch_pkgbase: "inetutils"
    repository: "only-core"
    build_order: 45
    enabled: true

  iproute2:
    version_source: "lfs"
    lfs_source_name: "iproute2"
    arch_pkgbase: "iproute2"
    repository: "only-core"
    build_order: 46
    enabled: true


  expat:
    version_source: "lfs"
    lfs_source_name: "expat"
    arch_pkgbase: "expat"
    repository: "only-core"
    build_order: 47
    enabled: true

  pcre2:
    version_source: "lfs"
    lfs_source_name: "pcre2"
    arch_pkgbase: "pcre2"
    repository: "only-core"
    build_order: 48
    enabled: true

  libtool:
    version_source: "lfs"
    lfs_source_name: "libtool"
    arch_pkgbase: "libtool"
    repository: "only-core"
    build_order: 49
    enabled: true

  autoconf:
    version_source: "lfs"
    lfs_source_name: "autoconf"
    arch_pkgbase: "autoconf"
    repository: "only-core"
    build_order: 50
    enabled: true

  automake:
    version_source: "lfs"
    lfs_source_name: "automake"
    arch_pkgbase: "automake"
    repository: "only-core"
    build_order: 51
    enabled: true

  elfutils:
    version_source: "lfs"
    lfs_source_name: "elfutils"
    arch_pkgbase: "elfutils"
    repository: "only-core"
    build_order: 52
    enabled: true


  linux-api-headers:
    version_source: "lfs"
    lfs_source_name: "linux"
    arch_pkgbase: "linux-api-headers"
    repository: "only-core"
    build_order: 53
    enabled: true

  tzdata:
    version_source: "lfs"
    lfs_source_name: "tzdata"
    arch_pkgbase: "tzdata"
    repository: "only-core"
    build_order: 54
    enabled: true

  shadow:
    version_source: "lfs"
    lfs_source_name: "shadow"
    arch_pkgbase: "shadow"
    repository: "only-core"
    build_order: 55
    enabled: true


  openssl:
    version_source: "lfs"
    lfs_source_name: "openssl"
    arch_pkgbase: "openssl"
    repository: "only-core"
    build_order: 56
    enabled: true

  perl:
    version_source: "lfs"
    lfs_source_name: "perl"
    arch_pkgbase: "perl"
    repository: "only-core"
    build_order: 57
    enabled: true

  perl-xml-parser:
    version_source: "lfs"
    lfs_source_name: "XML-Parser"
    arch_pkgbase: "perl-xml-parser"
    repository: "only-core"
    build_order: 58
    enabled: true

  intltool:
    version_source: "lfs"
    lfs_source_name: "intltool"
    arch_pkgbase: "intltool"
    repository: "only-core"
    build_order: 59
    enabled: true

  sqlite:
    version_source: "lfs"
    lfs_source_name: "sqlite-autoconf"
    arch_pkgbase: "sqlite"
    repository: "only-core"
    build_order: 60
    enabled: true

  ninja:
    version_source: "lfs"
    lfs_source_name: "ninja"
    arch_pkgbase: "ninja"
    repository: "only-core"
    build_order: 61
    enabled: true

  lz4:
    version_source: "lfs"
    lfs_source_name: "lz4"
    arch_pkgbase: "lz4"
    repository: "only-core"
    build_order: 62
    enabled: true

  tcl:
    version_source: "lfs"
    lfs_source_name: "tcl"
    arch_pkgbase: "tcl"
    repository: "only-core"
    build_order: 63
    enabled: true

  expect:
    version_source: "lfs"
    lfs_source_name: "expect"
    arch_pkgbase: "expect"
    repository: "only-core"
    build_order: 64
    enabled: true

  dejagnu:
    version_source: "lfs"
    lfs_source_name: "dejagnu"
    arch_pkgbase: "dejagnu"
    repository: "only-core"
    build_order: 65
    enabled: true

  kbd:
    version_source: "lfs"
    lfs_source_name: "kbd"
    arch_pkgbase: "kbd"
    repository: "only-core"
    build_order: 66
    enabled: true
