

  pkgconf:
    version_source: "lfs"
    lfs_source_name: "pkgconf"
    arch_pkgbase: "pkgconf"
    repository: "only-core"
    build_order: 31
    enabled: true

  binutils:
    version_source: "lfs"
    lfs_source_name: "binutils"
    arch_pkgbase: "binutils"
    repository: "only-core"
    build_order: 32
    enabled: true

  gperf:
    version_source: "lfs"
    lfs_source_name: "gperf"
    arch_pkgbase: "gperf"
    repository: "only-core"
    build_order: 33
    enabled: true

  libffi:
    version_source: "lfs"
    lfs_source_name: "libffi"
    arch_pkgbase: "libffi"
    repository: "only-core"
    build_order: 34
    enabled: true
